# Generated by Django 4.0.4 on 2022-06-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_alter_slider_slider_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_img', models.FileField(upload_to='clients/')),
            ],
        ),
        migrations.CreateModel(
            name='portfol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfol_img', models.FileField(upload_to='portfolio/')),
            ],
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_image',
            field=models.FileField(blank=True, null=True, upload_to='slid_imgs/'),
        ),
    ]
