# Generated by Django 4.0.4 on 2022-06-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_client_portfol_alter_slider_slider_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Enter company emal', max_length=254)),
                ('mobile', models.CharField(help_text='enter mobile number', max_length=20, unique=True)),
            ],
        ),
    ]
