# Generated by Django 4.0.4 on 2022-06-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='enter testimonial title here', max_length=100)),
                ('designation', models.CharField(help_text='enter designation here', max_length=100)),
                ('description', models.TextField(help_text='enter description here', max_length=100)),
                ('testi_img', models.FileField(upload_to='testimonialimages/')),
            ],
        ),
    ]
