# Generated by Django 4.0.4 on 2022-06-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0008_alter_team_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Your Name', max_length=100)),
                ('email', models.EmailField(help_text='Enter Your Email', max_length=100)),
                ('description', models.TextField(help_text='Enter Description Here', max_length=200)),
            ],
        ),
    ]
