# Generated by Django 4.0.4 on 2022-06-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0010_alter_user_description_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='slide_description',
            field=models.TextField(default='enter description', max_length=200),
        ),
        migrations.AddField(
            model_name='slider',
            name='slide_title',
            field=models.CharField(default='enter title', max_length=100),
        ),
    ]
