# Generated by Django 4.0.4 on 2022-06-25 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0011_slider_slide_description_slider_slide_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='enquiry',
        ),
    ]
