# Generated by Django 4.0.4 on 2022-06-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0012_rename_user_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tblrecentwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='enter title', max_length=100)),
                ('portfol_img', models.FileField(upload_to='portfolio/')),
                ('navigatelink', models.CharField(help_text='enter product navigate link', max_length=100)),
                ('description', models.TextField(help_text='enter product description', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='portfol',
        ),
    ]
