# Generated by Django 4.0.4 on 2022-06-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0014_tblrecentwork_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='c_name',
            field=models.CharField(default='enter client name', max_length=100),
        ),
    ]
