# Generated by Django 4.0.4 on 2022-06-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0015_client_c_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='client',
            new_name='Tblclient',
        ),
        migrations.RenameModel(
            old_name='contact',
            new_name='Tblcontact',
        ),
        migrations.RenameModel(
            old_name='enquiry',
            new_name='Tblenquiry',
        ),
        migrations.RenameModel(
            old_name='slider',
            new_name='Tblslider',
        ),
        migrations.RenameModel(
            old_name='Team',
            new_name='TblTeam',
        ),
        migrations.RenameModel(
            old_name='testimonial',
            new_name='Tbltestimonial',
        ),
    ]
