# Generated by Django 4.0.4 on 2022-07-02 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0018_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Story',
        ),
    ]
