# Generated by Django 4.1.5 on 2023-02-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0021_remove_story_body_remove_story_des_story_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblteam',
            name='fblink',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tblteam',
            name='inlink',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tblteam',
            name='linlink',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tblteam',
            name='twlink',
            field=models.CharField(default='', max_length=100),
        ),
    ]
